"""adding cannon to rubric

Revision ID: 0640e8f1b9ee
Revises: c40b6ba797f0
Create Date: 2017-07-17 21:11:23.222471

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0640e8f1b9ee'
down_revision = 'c40b6ba797f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rubric', sa.Column('canon', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rubric', 'canon')
    # ### end Alembic commands ###
