"""changed family_words to house_words

Revision ID: b6d657b32cce
Revises: c2be3dafbec6
Create Date: 2017-08-05 10:38:23.627370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6d657b32cce'
down_revision = 'c2be3dafbec6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('house_words', sa.String(), nullable=False))
    op.drop_constraint(u'user_family_words_key', 'user', type_='unique')
    op.create_unique_constraint(None, 'user', ['house_words'])
    op.drop_column('user', 'family_words')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('family_words', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user', type_='unique')
    op.create_unique_constraint(u'user_family_words_key', 'user', ['family_words'])
    op.drop_column('user', 'house_words')
    # ### end Alembic commands ###
