"""Adding description to the characters

Revision ID: baaef20b3358
Revises: 4755e4670611
Create Date: 2017-07-15 00:49:02.569275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'baaef20b3358'
down_revision = '4755e4670611'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('character', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('character', 'description')
    # ### end Alembic commands ###
