"""changed to draft history foreign key

Revision ID: c2be3dafbec6
Revises: 0640e8f1b9ee
Create Date: 2017-07-24 01:10:08.448377

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2be3dafbec6'
down_revision = '0640e8f1b9ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('score', sa.Column('draft_history_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_score_draft_history_id'), 'score', ['draft_history_id'], unique=False)
    op.drop_index('ix_score_draft_id', table_name='score')
    op.drop_constraint(u'score_draft_id_fkey', 'score', type_='foreignkey')
    op.create_foreign_key(None, 'score', 'draft_history', ['draft_history_id'], ['id'], ondelete='CASCADE')
    op.drop_column('score', 'draft_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('score', sa.Column('draft_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'score', type_='foreignkey')
    op.create_foreign_key(u'score_draft_id_fkey', 'score', 'draft', ['draft_id'], ['id'], ondelete=u'CASCADE')
    op.create_index('ix_score_draft_id', 'score', ['draft_id'], unique=False)
    op.drop_index(op.f('ix_score_draft_history_id'), table_name='score')
    op.drop_column('score', 'draft_history_id')
    # ### end Alembic commands ###
