"""Changing points to int

Revision ID: c40b6ba797f0
Revises: baaef20b3358
Create Date: 2017-07-15 02:16:55.480399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c40b6ba797f0'
down_revision = 'baaef20b3358'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
