"""Reset to clean version

Revision ID: 5a56694350e6
Revises: 
Create Date: 2017-07-04 22:26:24.340386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a56694350e6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('character',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('draft_ticket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_identifier', sa.String(), nullable=False),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_draft_ticket_sort'), 'draft_ticket', ['sort'], unique=False)
    op.create_index(op.f('ix_draft_ticket_user_identifier'), 'draft_ticket', ['user_identifier'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('identifier', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('icon', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('refresh_token', sa.String(), nullable=True),
    sa.Column('access_token', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('identifier'),
    sa.UniqueConstraint('name')
    )
    op.create_table('draft',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('drafted_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_draft_character_id'), 'draft', ['character_id'], unique=False)
    op.create_index(op.f('ix_draft_user_id'), 'draft', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_draft_user_id'), table_name='draft')
    op.drop_index(op.f('ix_draft_character_id'), table_name='draft')
    op.drop_table('draft')
    op.drop_table('user')
    op.drop_index(op.f('ix_draft_ticket_user_identifier'), table_name='draft_ticket')
    op.drop_index(op.f('ix_draft_ticket_sort'), table_name='draft_ticket')
    op.drop_table('draft_ticket')
    op.drop_table('character')
    # ### end Alembic commands ###
