"""Added details to user

Revision ID: b67bb925e344
Revises: 2861af832e0e
Create Date: 2017-06-25 12:02:50.056696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b67bb925e344'
down_revision = '2861af832e0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email', sa.String(), nullable=True))
    op.add_column('user', sa.Column('first_name', sa.String(), nullable=True))
    op.add_column('user', sa.Column('icon', sa.String(), nullable=True))
    op.add_column('user', sa.Column('identifier', sa.String(), nullable=True))
    op.add_column('user', sa.Column('last_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_name')
    op.drop_column('user', 'identifier')
    op.drop_column('user', 'icon')
    op.drop_column('user', 'first_name')
    op.drop_column('user', 'email')
    # ### end Alembic commands ###
